=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Ampliacion y refuerzo/ampliacion/natacion/Proves.dtd
<!ELEMENT Proves (Prova*)>
    <!ELEMENT Prova (Nom,Descripcio,Tipus,Data)>
        <!ATTLIST Prova id ID #REQUIRED>
        <!ELEMENT Nom (#PCDATA)>
        <!ELEMENT Descripcio (#PCDATA)>
        <!ELEMENT Tipus (#PCDATA)>
        <!ELEMENT Data (#PCDATA)>

=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Ampliacion y refuerzo/ampliacion/natacion/Proves.xml
<?xml version="1.0"?>
<?xml-model href="Proves.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!DOCTYPE Proves SYSTEM "Proves.dtd">
<Proves>
    <Prova id="AA1234">
        <Nom>Nombre de la Prueba</Nom>
        <Descripcio>Descripcion correspondiente a la prueba</Descripcio>
        <Tipus>Tipo de prueba</Tipus>
        <Data>1999-01-13</Data>
    </Prova>
    <Prova id="BB1234">
        <Nom>Nombre de la Prueba</Nom>
        <Descripcio>Descripcion correspondiente a la prueba</Descripcio>
        <Tipus>Tipo de prueba</Tipus>
        <Data>1999-01-13</Data>
    </Prova>
</Proves>
