=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Ampliacion y refuerzo/ampliacion/estudiantes/Colaboracions/Colaboracions.dtd
<!ELEMENT Colaboracions (Colaboracio*)>
    <!ELEMENT Colaboracio (Imparteix,Reb,Assignatura,Nivell,Hores,Estat,Avaluacio,DataInici,DataFin)>
        <!ATTLIST Colaboracio id ID #REQUIRED>
        <!ATTLIST Colaboracio refPeticio CDATA #REQUIRED>
        <!ELEMENT Imparteix (#PCDATA)>
        <!ELEMENT Reb (#PCDATA)>
        <!ELEMENT Assignatura (#PCDATA)>
        <!ELEMENT Nivell (#PCDATA)>
        <!ELEMENT Hores (#PCDATA)>
        <!ELEMENT Estat (#PCDATA)>
        <!ELEMENT Avaluacio (#PCDATA)>
        <!ELEMENT DataInici (#PCDATA)>
        <!ELEMENT DataFin (#PCDATA)>

=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Ampliacion y refuerzo/ampliacion/estudiantes/Colaboracions/Colaboracions.xml
<?xml version="1.0"?>
<!-- 
<!DOCTYPE Colaboracions SYSTEM "Colaboracions.dtd">
-->
<Colaboracions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Colaboracions.xsd">
    <Colaboracio id="AA123" refPeticio="AA123">
        <Imparteix>AA12345678</Imparteix>
        <Reb>AA12345678</Reb>
        <Assignatura>sistinform</Assignatura>
        <Nivell>Expert</Nivell>
        <Hores>1</Hores>
        <Estat>Actiu</Estat>
        <Avaluacio>3</Avaluacio>
        <DataInici>2002-09-24</DataInici>
        <DataFin>2003-09-24</DataFin>
    </Colaboracio>
    <Colaboracio id="AB123" refPeticio="AA123">
        <Imparteix>BB12345678</Imparteix>
        <Reb>AA12345678</Reb>
        <Assignatura>lenguajesmarcas</Assignatura>
        <Nivell>Principiant</Nivell>
        <Hores>1</Hores>
        <Estat>Actiu</Estat>
        <Avaluacio>4</Avaluacio>
        <DataInici>2002-09-24</DataInici>
        <DataFin>2003-09-24</DataFin>
    </Colaboracio>
</Colaboracions>
