=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Bloque 2/ejercicio 3/menu/menu.dtd
<!ELEMENT menu (entrantes, primeros, segundos, postres, bebidas)>
<!ATTLIST menu precio CDATA #REQUIRED>
<!ATTLIST menu horario CDATA #REQUIRED>

    <!ELEMENT entrantes (producto*)>
    <!ELEMENT primeros (producto*)>
    <!ELEMENT segundos (producto*)>
    <!ELEMENT postres (producto*)>
    <!ELEMENT bebidas (producto*)>

        <!ELEMENT producto (id, nombre, descripcion, alergenos, precio)>
            <!ELEMENT id (#PCDATA)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT descripcion (#PCDATA)>
            <!ELEMENT alergenos (#PCDATA)>
            <!ELEMENT precio (#PCDATA)>

=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Bloque 2/ejercicio 3/menu/menu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE menu SYSTEM "menu.dtd">

<menu precio="" horario="">
	<entrantes>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
	</entrantes>
	<primeros>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
	</primeros>
	<segundos>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
	</segundos>
	<postres>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
	</postres>
	<bebidas>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
		<producto>
			<id></id>
			<nombre></nombre>
			<descripcion></descripcion>
			<alergenos></alergenos>
			<precio></precio>
		</producto>
	</bebidas>
</menu>
