=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Ampliacion y refuerzo/refuerzo/dtd-xsd/Factura/Factura.dtd
<!ELEMENT Factura (Empresa, Fecha, Cliente, Vendedor, Precio, Iva, Descuento, Web)>
    <!ATTLIST Factura pagado CDATA "false">
    <!ATTLIST Factura formatoDePago CDATA #IMPLIED>
    <!ELEMENT Empresa (#PCDATA)>
    <!ELEMENT Fecha (#PCDATA)>
    <!ELEMENT Cliente (#PCDATA)>
    <!ELEMENT Vendedor (#PCDATA)>
    <!ELEMENT Precio (#PCDATA)>
    <!ELEMENT Iva (#PCDATA)>
    <!ELEMENT Descuento (#PCDATA)>
    <!ELEMENT Web (#PCDATA)>
<!ENTITY Empresa  "Tienda Virtual">
<!ENTITY WEB  "www.tiendavirtual.com">
<!ENTITY Fecha  "Octubre 2022">

=== nonamebruhyes/study/lenguajes-de-marcas/Ejercicios/Ampliacion y refuerzo/refuerzo/dtd-xsd/Factura/Factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Factura SYSTEM "Factura.dtd">
<?xml-model href="Factura.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<Factura pagado="false">
    <Empresa>&Empresa;</Empresa>
    <Fecha>&Fecha;</Fecha>
    <Cliente></Cliente>
    <Vendedor></Vendedor>
    <Precio>000,00â‚¬</Precio>
    <Iva></Iva>
    <Descuento></Descuento>
    <Web>&WEB;</Web>
</Factura>
